In [121]:
import numpy as np
import matplotlib.pyplot as plt

## ***Backward Substitution* algorithm**

In [122]:
test_A = np.array([
    [2, 1, 1],
    [0, 1, -2],
    [0, 0, 1]], dtype=float)
test_b = np.array([1, -1, 4], dtype=float)

In [123]:

def check_piv (A, indexes):
# Check if a given pivot row works out or gives problem with division
    row, col = indexes
    if A[row][col] == 0:
        for i in range(1, np.shape(A)[0]):
            if A[i][col] != 0:
                piv = i
                r1, r2 = 0, piv
                A[[r1,r2]] =A[[r2,r1]]
                print(f'Changed initial matrix A by pivoting rows {row} and {piv} because:\nA[0,0] = 0\n')
                print(A, '\n')  
                break
            
print(test_A, '\n')
print('Algorithm starts!')

def back_subst_dumb(A, b):
    # matrix must be a square matrix to be invertible
    n = np.shape(A)[0] - 1
    x_n = b[n] / A[n, n]
    np_x_i = np.zeros(n + 1)
    np_x_i[n] = x_n
    for i in np.flip(np.arange(n)):
        # using dot prod we can optimize the func
        # we sould see also entries useless but in np_x_i vector they are 0,
        # so they do not interfere with the computation algorithm
        x_i = (b[i] - np.sum(np.dot(A[i], np_x_i))) / A[i][i]
        np_x_i[i] = x_i
    print('\nSolution found:\nx =', np_x_i)
        
    print('\nTest true answer:')

    print('b =      ', b)
    print('A • x =  ', np.dot(A, np_x_i))

    return np_x_i

x = back_subst_dumb(test_A, test_b)


[[ 2.  1.  1.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]] 

Algorithm starts!

Solution found:
x = [-5.  7.  4.]

Test true answer:
b =       [ 1. -1.  4.]
A • x =   [ 1. -1.  4.]


## ***Gaussian Elimination* algorithm**

In [124]:
test_A = np.array([
    [2, 1,  1],
    [1, 1, -2],
    [1, 2,  1]], dtype=float)

test_b = np.array([8, -2, 2], dtype=float)

In [125]:
print(test_A, '\n')
print('Algorithm starts!\n')

piv = 0

def gauss_eli(A_in): 
    # the function do not touch the original matrix
    A = np.copy(A_in)
    n = np.shape(A)[0]
    for j in range(n-1):
        # print('Col =', j)
        for i in range(j+1, n):
            c = A[i,j] / A[j,j]
            A[i,:] -= c * A[j,:]

        #     print(f'Result on row {i}:\n{A}')
        # print()
    print(f'Reducted matrix by Gauss. red.:\n{A}')  
    return A

red_A = gauss_eli(test_A)

x = back_subst_dumb(red_A, test_b)


[[ 2.  1.  1.]
 [ 1.  1. -2.]
 [ 1.  2.  1.]] 

Algorithm starts!

Reducted matrix by Gauss. red.:
[[ 2.   1.   1. ]
 [ 0.   0.5 -2.5]
 [ 0.   0.   8. ]]

Solution found:
x = [ 5.25 -2.75  0.25]

Test true answer:
b =       [ 8. -2.  2.]
A • x =   [ 8. -2.  2.]


## ***Partial Pivoting modifier* algorithm**