In [22]:
import numpy as np
import matplotlib.pyplot as plt

## ***Backward Substitution* algorithm**

In [23]:
test_A = np.array([
    [2, 1, 1],
    [0, 1, -2],
    [0, 0, 1]], dtype=float)
test_b = np.array([1, -1, 4], dtype=float)

test_TA = test_A.T
test_Tb = np.flip(test_b)

In [24]:

def test_matrix(A_in, A_out):
    # returns True if the two corresponds
    print('\nA_test:\n', A_in)
    print('\nA_exp:\n', A_out)
    print('\nBoolean passed test =', np.allclose(A_in, A_out))

def check_piv (A_in, indexes):
# Check if a given pivot row works out or gives problem with division
    A = np.copy(A_in)
    row, col = indexes
    if A[row][col] == 0:
        for i in range(1, np.shape(A)[0]):
            if A[i][col] != 0:
                piv = i
                r1, r2 = 0, piv
                A[[r1,r2]] =A[[r2,r1]]
                print(f'Changed initial matrix A by pivoting rows {row} and {piv} because:\nA[{row},{[piv]}] = 0\n')
                print(A, '\n')  
                break
            
print(test_A, '\n')
print('Algorithm starts!')


def forw_subst_dumb(L, b, speak=False):
    if np.shape(L)[0] != np.shape(L)[1]:
        raise ValueError("Must use a square matrix!")

    n = np.shape(L)[0]
    np_xi = np.zeros(n)

    for i in range(n):
        x_i = (b[i] - np.dot(L[i, :i], np_xi[:i])) / L[i, i]
        np_xi[i] = x_i

    if speak:
        print('\nSolution found:\nx =', np_xi)
        print('\nTest true answer:')
        print('b =      ', b)
        print('L • x =  ', np.dot(L, np_xi))
    
    return np_xi

def back_subst_dumb(L, b, speak=False):
    if np.shape(L)[0] != np.shape(L)[1]:
        raise ValueError("Must use a square matrix!")

    n = np.shape(L)[0]
    np_xi = np.zeros(n)
    
    for i in reversed(range(n)):
        x_i = (b[i] - np.dot(L[i, i+1:], np_xi[i+1:])) / L[i, i]
        np_xi[i] = x_i

    if speak:
        print('\nSolution found:\nx =', np_xi)
        print('\nTest true answer:')
        print('b =      ', b)
        print('L • x =  ', np.dot(L, np_xi))
        
    return np_xi


x = back_subst_dumb(test_A, test_b, speak=True)
x = forw_subst_dumb(test_TA, test_Tb, speak=True)


[[ 2.  1.  1.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]] 

Algorithm starts!

Solution found:
x = [-5.  7.  4.]

Test true answer:
b =       [ 1. -1.  4.]
L • x =   [ 1. -1.  4.]

Solution found:
x = [ 2. -3. -7.]

Test true answer:
b =       [ 4. -1.  1.]
L • x =   [ 4. -1.  1.]


## ***Gaussian Elimination* algorithm**

In [25]:
test_A = np.array([
    [2, 1,  1],
    [1, 1, -2],
    [1, 2,  1]], dtype=float)

test_b = np.array([8, -2, 2], dtype=float)

In [26]:
print(test_A, '\n')
print('Algorithm starts!\n')

def gauss_eli(A_in): 
    # the function do not touch the original matrix
    A = np.copy(A_in)
    n = np.shape(A)[0]
    for j in range(n-1):
        # print('Col =', j)
        for i in range(j+1, n):
            c = A[i,j] / A[j,j]
            A[i,:] -= c * A[j,:]

        #     print(f'Result on row {i}:\n{A}')
        # print()
    print(f'Reducted matrix by Gauss. red.:\n{A}')  
    return A

red_A = gauss_eli(test_A)

x = back_subst_dumb(red_A, test_b)


[[ 2.  1.  1.]
 [ 1.  1. -2.]
 [ 1.  2.  1.]] 

Algorithm starts!

Reducted matrix by Gauss. red.:
[[ 2.   1.   1. ]
 [ 0.   0.5 -2.5]
 [ 0.   0.   8. ]]


## ***Inverse of a Matrix* algorithm**

In [27]:
test_A = np.array([
    # [2, 1,  1],
    # [1, 1, -2],
    # [1, 2,  1]], dtype=float)
    [2, 1,  1],
    [1, 0, -2],
    [1, 2,  1]], dtype=float)

print(test_A, '\n')

def M_inverter (A_in):
    A = np.copy(A_in)
    n = np.shape(A)[0]
    M = np.hstack((A, np.identity(n)))

    for j in range(n):
        piv = j
        check_piv(M[:, :n], (piv,j))
        # for i in range(n):


        
M_inverter(test_A)

    # return inv_A

[[ 2.  1.  1.]
 [ 1.  0. -2.]
 [ 1.  2.  1.]] 

Changed initial matrix A by pivoting rows 1 and 2 because:
A[1,[2]] = 0

[[ 1.  2.  1.]
 [ 1.  0. -2.]
 [ 2.  1.  1.]] 



## ***Partial Pivoting modifier* algorithm**