In [ ]:
import numpy as np
import matplotlib.pyplot as plt

import sys
import os
sys.path.append(os.path.abspath('..'))
from lib_algebra import forw_subst, back_subst, BackGauss, BackGauss_dumb, matrix_inverse


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## **Exercise 2.1.1**

1. **Write a function** that accepts an upper triangular matrix and implements the backward substitution. Test is on the linear system $U\mathbf{x} = \mathbf{b}$ with
   $$U = \begin{pmatrix} 2 & 1 & 1 \\ 0 & 1 & -2 \\ 0 & 0 & 1 \end{pmatrix}, \quad \mathbf{b} = \begin{pmatrix} 1 \\ -1 \\ 4 \end{pmatrix} \tag{2.1.10}$$
   and check that the solution is correct.

   > **Note:** You will use this function later on, so try to keep the code as modular as possible!

2. **Write a separate function** that performs Gaussian elimination and combine it with backward substitution to solve the system
   $$\begin{pmatrix} 2 & 1 & 1 \\ 1 & 1 & -2 \\ 1 & 2 & 1 \end{pmatrix} \begin{pmatrix} x_0 \\ x_1 \\ x_2 \end{pmatrix} = \begin{pmatrix} 8 \\ -2 \\ 2 \end{pmatrix} \tag{2.1.11}$$
   Check the solution. See the Appendices *Matrices* and *Modularity* for suggestions.

3. **Using the previous programs**, add a function that prints also the explicit inverse of a matrix. Test it on the matrix above and check the result.

4. **Adapt the previous programs** to include the partial pivoting and solve the following systems. Check that without partial pivoting the program fails, since at some intermediate step $A_{jj} = 0$ appears for the matrix
   $$\begin{pmatrix} 2 & 1 & 1 \\ 2 & 1 & -4 \\ 1 & 2 & 1 \end{pmatrix} \begin{pmatrix} x_0 \\ x_1 \\ x_2 \end{pmatrix} = \begin{pmatrix} 8 \\ -2 \\ 2 \end{pmatrix} \tag{2.1.12}$$

5. **Study the solution** to the problem
   $$\begin{pmatrix} 10^{-20} & -1 \\ 1 & 1 \end{pmatrix} \begin{pmatrix} x_0 \\ x_1 \end{pmatrix} = \begin{pmatrix} 1 \\ 2 \end{pmatrix} \tag{2.1.13}$$
   with and without pivoting. In this case the system is not ill-conditioned, i.e. it does not generate infinities, but produces the wrong result. Explain the origin of the error and why pivoting solves it.

## ***Backward Substitution* algorithm**

In [56]:
test_A = np.array([
    [2, 1, 1],
    [0, 1, -2],
    [0, 0, 1]], dtype=float)
test_b = np.array([1, -1, 4], dtype=float)

test_TA = test_A.T
test_Tb = np.flip(test_b)

# print('Algorithms start!')
print('U =\n', test_A)
print('\nb =', test_b)
x = back_subst (test_A, test_b, speak=True)
print()
print()
print('L =\n', test_TA)
print('\nb =', test_Tb)
y = forw_subst (test_TA, test_Tb, speak=True)

U =
 [[ 2.  1.  1.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]

b = [ 1. -1.  4.]

Solution found:
x = [-5.  7.  4.]


L =
 [[ 2.  0.  0.]
 [ 1.  1.  0.]
 [ 1. -2.  1.]]

b = [ 4. -1.  1.]

Solution found:
x = [ 2. -3. -7.]


## ***Gaussian Elimination* algorithm**

In [57]:
test_A = np.array([
    [2, 1,  1],
    [1, 1, -2],
    [1, 2,  1]], dtype=float)

test_b = np.array([8, -2, 2], dtype=float)

xi = BackGauss_dumb (test_A, test_b)
test = np.allclose(test_A @ xi, test_b)

print('A =\n', test_A)
print('b =', test_b, '\n')
print('x =', xi)

print(f'\nTest true answer: {test}')    # Prints True if the answer is correct after the check with b


A =
 [[ 2.  1.  1.]
 [ 1.  1. -2.]
 [ 1.  2.  1.]]
b = [ 8. -2.  2.] 

x = [ 4. -2.  2.]

Test true answer: True


## ***Inverse of a Matrix* algorithm**

In [58]:
test_A = np.array([
    [2, 1,  1],
    [1, 1, -2],
    [1, 2,  1]], dtype=float)

print('A =\n', test_A, '\n')
inv_A = matrix_inverse(test_A, True)

A =
 [[ 2.  1.  1.]
 [ 1.  1. -2.]
 [ 1.  2.  1.]] 

Solution found:
A^-1 =
 [[ 0.625  0.125 -0.375]
 [-0.375  0.125  0.625]
 [ 0.125 -0.375  0.125]]


## ***Partial Pivoting modifier* algorithm**

In [59]:

test_A = np.array([[2, 1, 1],
                   [2, 1, -4],
                   [1, 2, 1]], dtype=float)

test_b = np.array([8, -2, 2], dtype=float)

try:
    x = BackGauss_dumb (test_A, test_b)
    print("Solution:", x)
except Exception as e:
    print("An error occured!!:", e)

An error occured!!: Algorithm fails!
b != U • x


In [60]:
try:
    x = BackGauss(test_A, test_b)
    print('A =\n', test_A)
    print('b =', test_b, '\n')
    print("Solution:")
    print('x =', xi)
except Exception as e:
    print("An error occured!!:", e)

A =
 [[ 2.  1.  1.]
 [ 2.  1. -4.]
 [ 1.  2.  1.]]
b = [ 8. -2.  2.] 

Solution:
x = [ 4. -2.  2.]


## **An example of particular behaviour**

In [61]:
test_A = np.array([
    [1e-18, -1],
    [1, 1]
])

# Definizione del vettore b
test_b = np.array([1, 2])


xi = BackGauss_dumb(test_A, test_b)
test = np.allclose(test_A @ xi, test_b)

print('A =\n', test_A, '\n')
print()

print('x_dumb =', xi)
print(f'\nTest true answer: {test}')    # Prints True if the answer is correct after the check with b


xi = BackGauss(test_A, test_b)
test = np.allclose(test_A @ xi, test_b)

print('\n\nx_true =', xi)
print(f'\nTest true answer: {test}')    # Prints True if the answer is correct after the check with b

A =
 [[ 1.e-18 -1.e+00]
 [ 1.e+00  1.e+00]] 


x_dumb = [ 0. -1.]

Test true answer: False


x_true = [ 3. -1.]

Test true answer: True
