## **Decomposizione QR con Riflessioni di Householder**

Write a program that accepts a matrix $A$ and returns the matrices $Q$ and $R$. Test it on the matrix

$$
A = \begin{pmatrix} 
12 & -51 & 4 \\ 
6 & 167 & -68 \\ 
-4 & 24 & -41 
\end{pmatrix}
$$

A generic template (to be filled) for a QR function based on the previously introduced Householder reflector is:

```python
function QR(A):
    Q = identity nxn
    R = copy of A such that A is left untouched
    for i in range(...):
        Pp = householder( sub-block of R defined by i )
        P = manipulation of Pp to turn it into the appropriate nxn matrix
        R = P.R
        Q = Q.P
        
    return Q and R

In [ ]:
import numpy as np

import sys
import os
sys.path.append(os.path.abspath('..'))
from lib_algebra import householder_2x2, QR_dec, back_subst, determinant


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## **Matrice 2x2**

In [31]:
A_test = np.round(np.random.rand(2,2), 2) * 100

Q = householder_2x2(A_test)
R = Q.T@A_test

print('A =\n', A_test, '\n')
print('R =\n', R, '\n')
print('Q =\n', Q)

A =
 [[43. 77.]
 [95. 86.]] 

R =
 [[-1.04278473e+02 -1.10099425e+02]
 [-7.99360578e-15 -3.46859700e+01]] 

Q =
 [[-0.4123574  -0.91102216]
 [-0.91102216  0.4123574 ]]


### **Calcolo determinante con numpy in un'unica operazione**

In [32]:
# det_test = np.round((np.random.rand(3,3) * 100) * np.array([1,2,3]), 0)
# print(det_test)

# det = det_test[:]

## **Matrice nxn**

In [33]:
A_dim = 3
A_test = np.round(np.random.rand(A_dim, A_dim), 2) * 100    

Q, R = QR_dec(A_test)

print('\nFINAL RESULTS')
print('A =\n', A_test, '\n')
print('R =\n', R, '\n')
print('Q =\n', Q)


FINAL RESULTS
A =
 [[39. 32. 52.]
 [18. 42. 16.]
 [74.  6. 10.]] 

R =
 [[-8.55628424e+01+0.j -2.86105502e+01+0.j -3.57164385e+01+0.j]
 [ 8.99346882e-15+0.j -4.47820993e+01+0.j -3.06848733e+01+0.j]
 [ 1.28208390e-14+0.j  4.89672050e-15+0.j -2.90305799e+01+0.j]] 

Q =
 [[-0.45580533+0.j -0.42336467+0.j -0.78294563+0.j]
 [-0.21037169+0.j -0.80347172+0.j  0.55693532+0.j]
 [-0.8648614 +0.j  0.41856369+0.j  0.27716275+0.j]]


## **Determinant of a Matrix**

In [34]:

LU = determinant(A_test, choice='LU')
QR = determinant(A_test, choice='QR')

print(A_test)
print()
print('LU det =', LU)
# Chol = determinant_Chol(A_test)
# print(Chol)
print('QR det =', QR)

[[39. 32. 52.]
 [18. 42. 16.]
 [74.  6. 10.]]

LU det = -111235.99999999999
QR det = -111235.99999999996


## **Linear solver QR**

In [35]:
A_test = np.array([[3, 2, -1],
              [2, -2,  4],
              [-1, 0.5, -1]])
b_test = np.array([1, -2, 0])

def QR_solver(A, b):
    """
    Solve a linear system using QR decomposition and Backward substitution.
    """
    Q,R = QR_dec(A)
    x_sol = back_subst(R, Q.T @ b, speak=True)
    return x_sol 

QR_solver(A_test, b_test)
    


Solution found:
x = [ 1.-0.j -2.+0.j -2.+0.j]


array([ 1.-0.j, -2.+0.j, -2.+0.j])