## **Decomposizione QR con Riflessioni di Householder**

Write a program that accepts a matrix $A$ and returns the matrices $Q$ and $R$. Test it on the matrix

$$
A = \begin{pmatrix} 
12 & -51 & 4 \\ 
6 & 167 & -68 \\ 
-4 & 24 & -41 
\end{pmatrix}
$$

A generic template (to be filled) for a QR function based on the previously introduced Householder reflector is:

```python
function QR(A):
    Q = identity nxn
    R = copy of A such that A is left untouched
    for i in range(...):
        Pp = householder( sub-block of R defined by i )
        P = manipulation of Pp to turn it into the appropriate nxn matrix
        R = P.R
        Q = Q.P
        
    return Q and R

In [3]:
import numpy as np

%load_ext autoreload
%autoreload 2

import sys
import os
sys.path.append(os.path.abspath('..'))
from lib_algebra import householder_2x2, QR_dec, LU_dec, chol_fact, back_subst


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## **Matrice 2x2**

In [4]:
A_test = np.round(np.random.rand(2,2), 2) * 100

Q = householder_2x2(A_test)
R = Q.T@A_test

print('A =\n', A_test, '\n')
print('R =\n', R, '\n')
print('Q =\n', Q)

A =
 [[ 4. 84.]
 [72. 59.]] 

R =
 [[-7.21110255e+01 -6.35686425e+01]
 [ 3.99680289e-15 -8.05979385e+01]] 

Q =
 [[-0.05547002 -0.99846035]
 [-0.99846035  0.05547002]]


### **Calcolo determinante con numpy in un'unica operazione**

In [5]:
# det_test = np.round((np.random.rand(3,3) * 100) * np.array([1,2,3]), 0)
# print(det_test)

# det = det_test[:]

## **Matrice nxn**

In [6]:
A_dim = 3
A_test = np.round(np.random.rand(A_dim, A_dim), 2) * 100    

Q, R = QR_dec(A_test)

print('\nFINAL RESULTS')
print('A =\n', A_test, '\n')
print('R =\n', R, '\n')
print('Q =\n', Q)


FINAL RESULTS
A =
 [[83.  8. 90.]
 [73. 81.  3.]
 [81. 54. 53.]] 

R =
 [[-1.37036491e+02 -7.99130208e+01 -8.74365643e+01]
 [-6.27562996e-15 -5.61685775e+01  5.63005176e+01]
 [ 1.08547104e-14  2.47429210e-15  1.01537651e+01]] 

Q =
 [[-0.60567809  0.71929124 -0.34025604]
 [-0.53270482 -0.68418945 -0.49810678]
 [-0.59108343 -0.12043633  0.79756847]]


## **Determinant of a Matrix**

In [7]:

LU = determinant_LU(A_test)
QR = determinant_QR(A_test)

print(A_test)
print('LU det =', LU)
# Chol = determinant_Chol(A_test)
# print(Chol)
print('QR det =', QR)

NameError: name 'determinant_LU' is not defined

## **Linear solver QR**

In [ ]:
A_test = np.array([[3, 2, -1],
              [2, -2,  4],
              [-1, 0.5, -1]])
b_test = np.array([1, -2, 0])

def QR_solver(A, b):
    """
    Solve a linear system using QR decomposition and Backward substitution.
    """
    Q,R = QR_dec(A)
    x_sol = back_subst(R, Q.T @ b, speak=True)
    return x_sol 

QR_solver(A_test, b_test)
    


Solution found:
x = [ 1. -2. -2.]


array([ 1., -2., -2.])