## **Decomposizione QR con Riflessioni di Householder**

Write a program that accepts a matrix $A$ and returns the matrices $Q$ and $R$. Test it on the matrix

$$
A = \begin{pmatrix} 
12 & -51 & 4 \\ 
6 & 167 & -68 \\ 
-4 & 24 & -41 
\end{pmatrix}
$$

A generic template (to be filled) for a QR function based on the previously introduced Householder reflector is:

```python
function QR(A):
    Q = identity nxn
    R = copy of A such that A is left untouched
    for i in range(...):
        Pp = householder( sub-block of R defined by i )
        P = manipulation of Pp to turn it into the appropriate nxn matrix
        R = P.R
        Q = Q.P
        
    return Q and R

In [ ]:
import numpy as np

%load_ext autoreload
%autoreload 2

import sys
import os
sys.path.append(os.path.abspath('..'))
from lib_algebra import householder_2x2, QR_dec, back_subst


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## **Matrice 2x2**

In [ ]:
A_test = np.round(np.random.rand(2,2), 2) * 100

Q = householder_2x2(A_test)
R = Q.T@A_test

print('A =\n', A_test, '\n')
print('R =\n', R, '\n')
print('Q =\n', Q)

A =
 [[64. 11.]
 [96. 56.]] 

R =
 [[-1.15377641e+02 -5.26965186e+01]
 [-2.48689958e-14  2.19106578e+01]] 

Q =
 [[-0.5547002  -0.83205029]
 [-0.83205029  0.5547002 ]]


### **Calcolo determinante con numpy in un'unica operazione**

In [ ]:
# det_test = np.round((np.random.rand(3,3) * 100) * np.array([1,2,3]), 0)
# print(det_test)

# det = det_test[:]

## **Matrice nxn**

In [ ]:
A_dim = 3
A_test = np.round(np.random.rand(A_dim, A_dim), 2) * 100    

Q, R = QR_dec(A_test)

print('\nFINAL RESULTS')
print('A =\n', A_test, '\n')
print('R =\n', R, '\n')
print('Q =\n', Q)

TypeError: copy() got an unexpected keyword argument 'dtype'

## **Determinant of a Matrix**

In [ ]:

LU = determinant_LU(A_test)
QR = determinant_QR(A_test)

print(A_test)
print('LU det =', LU)
# Chol = determinant_Chol(A_test)
# print(Chol)
print('QR det =', QR)

NameError: name 'determinant_LU' is not defined

## **Linear solver QR**

In [ ]:
A_test = np.array([[3, 2, -1],
              [2, -2,  4],
              [-1, 0.5, -1]])
b_test = np.array([1, -2, 0])

def QR_solver(A, b):
    """
    Solve a linear system using QR decomposition and Backward substitution.
    """
    Q,R = QR_dec(A)
    x_sol = back_subst(R, Q.T @ b, speak=True)
    return x_sol 

QR_solver(A_test, b_test)
    


Solution found:
x = [ 1. -2. -2.]


array([ 1., -2., -2.])