## **Exercise 2.2.1**

Write a program that accepts a matrix $A$, checks that it is symmetric (if real) and then returns the **Cholesky factor** $L$.

1. Test the program on the matrix
   $$
   A = \begin{pmatrix} 
   4 & 12 & -16 \\ 
   12 & 37 & -43 \\ 
   -16 & -43 & 98 
   \end{pmatrix}
   $$
   and check the correctness of the result. This program will be useful later on.

2. Write a solver that wraps together Cholesky factorization with **backward and forward substitutions**.

3. Calculate the Laplacian matrix $K$ and the vector $b$ using:
   * $4\pi\varepsilon_0 = 1.0$
   * $L = 1.0$
   * $N = 50$
   * Gaussian distributed charge density $\rho(x) = e^{-R(x-0.5)^2}$

   Solve the linear system for the cases $R = 100$ and $R = 10$ using the solver based on Cholesky's decomposition.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Definizione delle costanti del problema e della matrice di test
L = 1.0
N_points = 50
R1 = 100
R2 = 10

rho_1 = np.exp(-R1 * (np.linspace(0, L, N_points) - 0.5))
rho_2 = np.exp(-R2 * (np.linspace(0, L, N_points) - 0.5))

A_test = np.array([
    [4, 12, -16],
    [12, 37, -43],
    [-16, -43, 98]
], dtype=np.float64)

In [3]:

def chol_fact(A):
    n = np.shape(A)
    # Must be a square matrix
    if A.shape[0] != A.shape[1]:
        raise ValueError("Must use a square matrix!")

    # Check if symmetric
    if not np.allclose(A, A.T, atol=1e-8):
        raise ValueError(f'A is not symmetric! Max distance between matrices: {np.max(np.abs(A - A.T)):.2e}')

    L = np.zeros(shape=n, dtype=np.float64)
    for i in range(n[0]):
        for j in range(n[0]):
            if i == j:
            # Diagonal elements
                L[i][i] = np.sqrt(A[i][i] - np.sum(L[i][:i]**2))
            elif i > j:
            # Off diagonal
                sec = max(i-2, 1)
                L[i][j] = 1 / L[j][j] * (A[i][j] - np.sum(np.dot(L[i][:sec], L[j][:sec])))
    print('\nCholesky factor (L):\n', L)
    return L


L = chol_fact(A_test)
A_exp = L @ L.conj().T
A_diff = A_test - A_exp

print('\n-------------------- TEST --------------------')
print('\nA_test:\n', A_test)
print('\nA_exp:\n', A_exp)
print('\nBoolean passed test =', np.allclose(A_test, A_exp))


Cholesky factor (L):
 [[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]

-------------------- TEST --------------------

A_test:
 [[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]

A_exp:
 [[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]

Boolean passed test = True
